SELECT
O.O_ORDERDATE AS ORDER_DATE,
G.N_NAME AS COUNTRY,
G.R_NAME AS CONTINENT,
O.SRC,
SUM(O.O_TOTALPRICE) AS TOTAL_SALES,
COUNT(*) AS NUM_ORDERS
FROM {{ ref('mart__fact_orders') }} O
LEFT JOIN {{ ref('mart__dim_customer') }} C
ON O.C_HASHKEY = C.HASHKEY
LEFT JOIN {{ ref('mart__outrigger_geography') }} G
ON C.C_NATIONKEY = G.N_NATIONKEY
GROUP BY O.O_ORDERDATE, G.N_NAME, G.R_NAME, O.SRC