version: 2

sources:
  - name: TPCH
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: CUSTOMER
      - name: LINEITEM
      - name: NATION
      - name: PART
      - name: PARTSUPP
      - name: REGION
      - name: ORDERS
      - name: SUPPLIER

  - name: TEST
    database: DV_DB
    schema: TEST
    tables:
      - name: SRC